### ISSUE TITLE
api Url  https://api.jublo.net/codebird/oauth/request_token is getting 403.

### ISSUE THREAD

**Issue by chinna-magapu** [jublo/codebird-js#155]
Hi I am using codebird-js for twitter authentication. It is working fine But now the below api url is getting 403 status. can any one please help me how to sort this.
https://api.jublo.net/codebird/oauth/request_token

**Comment by aplaskota** [comment]
Hi, I have the same issue in my app. @chinna-magapu did you resolve it?

**Comment by mynetx** [comment]
This could be related to Twitter being stricter with their callback URLs for oauth/request_token now. Please update your code to use Codebird 3.0.0 Beta 2: https://github.com/jublonet/codebird-js/tree/729325b

Let me know if this helps you.
You can find more information in #156.

**Comment by mynetx** [comment]
Closing due to no further replies.
